### ISSUE TITLE
CSS3

### ISSUE THREAD

**Issue by nicoleJT914** [nicoleJT914/blog#30]
### 绘制三角形
```css
#tra {
  width: 0;
  height: 0;
  border-bottom: 100px solid pink;
  border-left: 50px solid transparent;
  border-right: 50px solid transparent;
}
```

**Comment by nicoleJT914** [comment]
### `rem`
rem相对根元素<html>  
em相对其父元素的`font-size`  
对rem的计算简化  
```css
html{
font-size:62.5%; /* 10÷16=62.5% */
}
body{
font-size:12px;
font-size:1.2rem ; /* 12÷10=1.2 */
}
p{
font-size:14px;
font-size:1.4rem;
}
```
当然使用CSS预处理器，计算rem就不在话下了
